### ISSUE TITLE
Fix 'email_rfc822' content field support

### ISSUE THREAD

**Issue by ewandennis** [SparkPost/node-sparkpost#124] opened 2016-03-23 16:31 UTC
Transmissions using the `content.email_rfc822` form of content will currently fail with:
```
{ [SparkPostError: Unprocessable Entity]
  name: 'SparkPostError',
  errors:
   [ { message: 'required field is missing',
       description: 'No valid fields exist in the \'content\' object',
       code: '1400' } ],
  statusCode: 422 }
```

The problem is `toApiFormat()` that unfortunately converts all keys under `content` to snake case.

**Comment by orval** [comment] 2016-03-23 17:43
Note that branch ISSUE-124 has been created to address this. However all that has been pushed so far is a test that reproduces the issue.

**Comment by aydrian** [comment] 2016-03-24 16:53
Can this be included in 1.3.0? Or is this a breaking change that needs to be addressed in `wip-2.0.0` for the major release bump? Can you please set the milestone accordingly? Thanks.

**Comment by orval** [comment] 2016-03-26 11:46
Originally I would have said this is not a breaking change, but I've been doing some testing this morning and found that there may be a further, related issue. It may be best to have a chat about it, to work out what the expected behaviour should be.

Here is some partial code:
```js
    transmissionBody: {
      substitutionData: {
        firstName: 'Tarquin',
        surname: 'Biscuitbarrel'
      },
      content: {
        text: 'Congratulations, {{firstName}} {{surname}}!! You just sent your very first mailing!',
```

This results in:
> Congratulations,  Biscuitbarrel!! You just sent your very first mailing!

This is the expected result:
> Congratulations, Tarquin Biscuitbarrel!! You just sent your very first mailing!

To get that, you need to use `substitution_data` rather than `substitutionData`. This is because the `excludeList` in `toApiFormat.js` uses snake case to specify the exclusions.

This seems wrong to me, since we expect users to have `substitutionData:` in their code. But to fix that is a breaking change.

**Comment by orval** [comment] 2016-04-04 12:05
I have pushed to this branch various tests that demonstrate the issues in toApiFormat.js.

**Closed** 2016-04-05 07:55 UTC
